### ISSUE TITLE
ipywidgets not working 

### ISSUE THREAD

**Issue by scimax** [RustyVermeer/tryCQ#1]
I tried to open the Example 1 *Simple Block* and also other examples in mybinder but, on execution, it always displays
```
Widget Javascript not detected.  It may not be installed or enabled properly.

A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.
```
I'm new to mybinder. I tried to figure out where the problem originates from but I was not succesfull.

Tried with:
- Firefox 59
- Edge 41

**Comment by zbynekwinkler** [comment]
I am getting the same message with Firefox 60.

**Comment by adam-james-v** [comment]
I also see this error in the latest stable release of Chrome.

Apologies for not seeing this right away.
I will have to look into the problem and do what I can in the next few days.

**Comment by adam-james-v** [comment]
I have a [new binder link](https://mybinder.org/v2/gh/RustyVermeer/tryCQ/widget-fix)

Before I push the [widget-fix](https://github.com/RustyVermeer/tryCQ/tree/widget-fix) branch to master, do you @scimax and @zwn mind checking that the binder works for you as well?

**Comment by adam-james-v** [comment]
I should note that I have this working on Chrome and Firefox (latest of both).

If you see widget related errors when you initially load the notebook (before you have done anything yourself), please try:

- click the cell which is displaying the error
- RUN that cell's code
- it *should* clear the error and display some input boxes. At the bottom will be a button 'Run Interact'
- press that button and below should appear the 3d model.

**Comment by zbynekwinkler** [comment]
I no longer see any errors.

**Comment by scimax** [comment]
I tested four examples and all of them were running fine. This looks great!

(Firefox 60)

**Comment by adam-james-v** [comment]
@scimax @zwn , thank you both for letting me know the issue and then testing it out now.

I will push to master and make sure the README is updated! :)
